name: Dependency-Track SBOM Analysis with Debug

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-track:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (adjust version as needed)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Change to your project's Node.js version

      # Step 3: Debug secrets (check if they are set without revealing values)
      - name: Debug Secrets
        run: |
          echo "DEPENDENCYTRACK_SERVER is set: ${{ secrets.DEPENDENCYTRACK_SERVER != '' }}"
          echo "DEPENDENCYTRACK_APIKEY is set: ${{ secrets.DEPENDENCYTRACK_APIKEY != '' }}"

      # Step 4: Test connectivity to Dependency-Track server
      - name: Test Connectivity to Dependency-Track
        run: |
          curl -v https://${{ secrets.DEPENDENCYTRACK_SERVER }}/api/version
        continue-on-error: true  # Continue even if this fails to capture logs

      # Step 5: Install dependencies and generate CycloneDX SBOM
      - name: Generate SBOM
        run: |
          npm ci  # Install project dependencies
          npm install -g @cyclonedx/cyclonedx-npm
          npx cyclonedx-npm --output-format XML --output-file bom.xml

      # Step 6: Check if BOM file exists and is readable
      - name: Check BOM File
        run: |
          ls -l bom.xml || echo "BOM file not found"
          cat bom.xml || echo "BOM file is empty or unreadable"

      # Step 7: Upload SBOM to Dependency-Track with continue-on-error
      - name: Upload SBOM to Dependency-Track
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          serverHostname: ${{ secrets.DEPENDENCYTRACK_SERVER }}  # Ngrok URL (e.g., abc123.ngrok.io)
          apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}  # Stored in GitHub Secrets
          projectName: 'MyProject'  # Replace with your project name
          projectVersion: '1.0'  # Replace with your project version
          bomFilename: 'bom.xml'
          autoCreate: true
        continue-on-error: true  # Continue to see full logs even if upload fails
