name: Dependency Check PoC

on: [push]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    name: Dependency Check Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build project with Maven
        run: mvn clean install -DskipTests

      - name: Run Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'dependency-check-poc'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --failOnCVSS 5  # Falha se CVSS >= 5 (para capturar vulnerabilidades moderadas)
            --enableRetired

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ${{ github.workspace }}/reports
