name: Dependency Check PoC

on: [push]

permissions:
  issues: write
  contents: read

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    name: Dependency Check Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List directory contents
        run: ls -la

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Verify Java installation
        run: |
          echo "JAVA_HOME is set to: $JAVA_HOME"
          java -version
          which java

      - name: Fix JAVA_HOME for Docker
        run: |
          echo "JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.26-4/x64" >> $GITHUB_ENV
          echo "PATH=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.26-4/x64/bin:$PATH" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm install || echo "Nenhum package.json encontrado"

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: depcheck
        with:
          project: 'dependency-check-poc'
          path: '.'
          format: 'ALL'
          out: 'reports'
          args: >
            --failOnCVSS 7
            --enableRetired
            --noupdate

      - name: List reports directory contents
        if: always()
        run: ls -la ${{ github.workspace }}/reports

      - name: Upload Dependency Check Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ${{ github.workspace }}/reports

      - name: Check for vulnerabilities and create issue
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const reportPath = '${{ github.workspace }}/reports/dependency-check-report.json';
            console.log(`Attempting to read report at: ${reportPath}`);
            if (!fs.existsSync(reportPath)) {
              console.error(`Report file not found at ${reportPath}`);
              return;
            }
            const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));

            const vulnerabilities = report.dependencies
              .filter(dep => dep.vulnerabilities && dep.vulnerabilities.length > 0)
              .map(dep => {
                const criticalVulns = dep.vulnerabilities.filter(v => {
                  let score = -1;
                  if (v.cvssv3 && v.cvssv3.baseScore) {
                    score = v.cvssv3.baseScore;
                  } else if (v.cvssv2 && v.cvssv2.score && v.cvssv2.score !== -1.0) {
                    score = v.cvssv2.score;
                  }
                  return score >= 7;
                });
                if (criticalVulns.length > 0) {
                  let libraryName = 'Unknown';
                  if (dep.packages && dep.packages.length > 0) {
                    const packageId = dep.packages[0].id;
                    libraryName = packageId.split('@')[0].replace('pkg:gem/', '').replace('pkg:npm/', '');
                  }
                  const workspace = '${{ github.workspace }}';
                  let filePath = dep.filePath;
                  if (filePath.startsWith(workspace)) {
                    filePath = filePath.substring(workspace.length + 1);
                  }
                  let lineNumber = 'Unknown';
                  let snippet = 'Unknown';
                  try {
                    if (fs.existsSync(dep.filePath)) {
                      const content = fs.readFileSync(dep.filePath, 'utf8').split('\n');
                      for (let i = 0; i < content.length; i++) {
                        if (content[i].includes(libraryName)) {
                          lineNumber = i + 1;
                          snippet = content[i].trim();
                          break;
                        }
                      }
                    }
                  } catch (error) {
                    console.error(`Error reading file ${dep.filePath}: ${error}`);
                  }
                  const vulnDetails = criticalVulns.map(v => {
                    let score = 'Unknown';
                    if (v.cvssv3 && v.cvssv3.baseScore) {
                      score = v.cvssv3.baseScore;
                    } else if (v.cvssv2 && v.cvssv2.score) {
                      score = v.cvssv2.score;
                    }
                    return `${v.name} (CVSS: ${score})`;
                  });
                  return {
                    filePath: filePath,
                    libraryName: libraryName,
                    lineNumber: lineNumber,
                    snippet: snippet,
                    vulns: vulnDetails
                  };
                }
                return null;
              })
              .filter(dep => dep !== null);

            if (vulnerabilities.length > 0) {
              const issueBody = `
              ## Vulnerabilidades Detectadas

              O Dependency-Check identificou as seguintes vulnerabilidades com CVSS >= 7:

              ${vulnerabilities.map(v => `- Arquivo: ${v.filePath}, Biblioteca: ${v.libraryName}, Linha ${v.lineNumber}: '${v.snippet}' (vulnerável a ${v.vulns.join(', ')})`).join('\n')}

              Por favor, revise o relatório completo em anexo e tome as ações necessárias.
              `;
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Vulnerabilidades Críticas Detectadas pelo Dependency-Check',
                body: issueBody,
                assignees: [context.actor]
              });
            } else {
              console.log('No vulnerabilities with CVSS >= 7 found.');
            }
