name: Dependency Check PoC
on: [push]
permissions:
  contents: read
  security-events: write

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    name: Dependency Check Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for better vulnerability scanning
      
      - name: List directory contents
        run: ls -la
      
      # Install OSV Scanner CLI directly
      - name: Install OSV Scanner
        run: |
          curl -fsSL https://github.com/google/osv-scanner/releases/download/v1.3.0/osv-scanner_1.3.0_linux_amd64 -o osv-scanner
          chmod +x osv-scanner
          sudo mv osv-scanner /usr/local/bin/
      
      # Run OSV Scanner and generate SARIF output
      - name: Run OSV Scanner with SARIF output
        run: |
          osv-scanner --format sarif --recursive . > osv-scan-results.sarif
      
      # Upload the SARIF file to GitHub Security tab
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: osv-scan-results.sarif
          category: osv-scanner
      
      # Run detailed scan with CLI for JSON output
      - name: Run detailed scan with CLI
        run: |
          osv-scanner --json --recursive . > osv-scanner-detailed.json
          osv-scanner --lockfile="**/package-lock.json" --lockfile="**/go.mod" --lockfile="**/Cargo.lock" --lockfile="**/Gemfile.lock" --lockfile="**/requirements.txt" --lockfile="**/composer.lock" --lockfile="**/pom.xml" --json > osv-scanner-lockfiles.json
      
      # Save detailed scan results as artifacts
      - name: Upload detailed scan results
        uses: actions/upload-artifact@v4
        with:
          name: osv-scanner-results
          path: |
            osv-scanner-detailed.json
            osv-scanner-lockfiles.json
          retention-days: 7
